Task_004/Models/Book.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Task_004.Models
{
    public class Book
    {
        public int Id { get; set; }

        public string Name { get; set; }

        [Range(1, 5000, ErrorMessage = "Too many pages... Recheck the quontity!")]
        [DisplayName("Page QTY")]
        public int PageQty { get; set; }

        public Genre Genre { get; set; }
        public ICollection<Author> Authors { get; set; } = new List<Author>();

        public override string ToString()
        {
            return $"\"{Name}\", {PageQty} page(s) total and it's \"{Genre}\" by genre";
        }
    }

    public enum Genre : byte
    {
        AvantGarde, Action, Detective,
        Historical, Love
    }
}

Task_004/Models/Entities/Book.cs
namespace Task_004.Models.Entities
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PageQty { get; set; }
        public Genre Genre { get; set; }
        public ICollection<Author> Authors { get; set; } = new List<Author>();
    }

    public enum Genre : byte
    {
        AvantGarde, Action, Detective, 
        Historical, Love, Mystic, 
        Adventures, Thriller, Horror
    }
}

Task_004/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Task_004.Models;
using Task_004.ViewModels;

namespace Task_004.Controllers
{
    public class BooksController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public BooksController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Book> objBooksList = await _db.Books.Include(x => x.Authors).ToListAsync();
            return View(objBooksList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Book book)
        {
            if (ModelState.IsValid)
            {
                _db.Books.Add(book);
                await _db.SaveChangesAsync();
                TempData["success"] = "The book has been created succesfully!";
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null)
            {
                Book? book = await _db.Books.FirstOrDefaultAsync(x => x.Id == id);
                return View(book);
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book)
        {
            if (ModelState.IsValid)
            {
                _db.Books.Update(book);
                await _db.SaveChangesAsync();
                TempData["success"] = "The book has been edited succesfully!";
                return RedirectToAction("Index");
            }
            return View(book);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null)
            {
                Book? book = await _db.Books.FirstOrDefaultAsync(x => x.Id == id);
                if (book != null)
                {
                    _db.Books.Remove(book);
                    await _db.SaveChangesAsync();
                    TempData["success"] = "Book has been delited succesfully!";
                    return RedirectToAction("Index");
                }
            }
            return NotFound();
        }

        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id != null)
            {
                Book? book = await _db.Books.Include(x => x.Authors).FirstOrDefaultAsync(x => x.Id == id);
                return View(book);
            }
            return NotFound();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Task_004/Views/Books/Create.cshtml
@model Book
@{
    ViewData["Title"] = "Create an Author";
}

<form method="post" style="width: 100%; margin: auto">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2>Create</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PageQty"></label>
            <input asp-for="PageQty" class="form-control">
            <span asp-validation-for="PageQty" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Genre"></label>
            <select asp-for="Genre" class="form-select" id="exampleSelect1">
                <option value="0">AvantGarde</option>
                <option value="1">Action</option>
                <option value="2">Detective</option>
                <option value="3">Historical</option>
                <option value="4">Love</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">
            <i class="bi bi-check-square"></i> &nbsp; Create
        </button>
        <a asp-controller="Books" asp-action="Index" class="btn btn-secondary" style="width:150px">
            <i class="bi bi-x-circle"></i> &nbsp; Cancel
        </a>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />}

Task_004/Views/Books/Details.cshtml
@model Book
@{
    ViewData["Title"] = "Details";
}

<form>
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Details</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="PageQty"></label>
            <input asp-for="PageQty" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label asp-for="Genre"></label>
            <input asp-for="Genre" disabled class="form-control">
        </div>
        <div class="mb-3">
            <label>by</label>
                @foreach (var item in Model.Authors)
                {
                    @item
                }
        </div>
        <a asp-controller="Books" asp-action="Index" class="btn btn-secondary" style="width:150px">
            <i class="bi bi-x-circle"></i> &nbsp; Back
        </a>
    </div>
</form>

Task_004/Views/Books/Edit.cshtml
@model Book
@{
    ViewData["Title"] = "Edit";
}

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-light">Edit</h2>
            <hr />
        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PageQty"></label>
            <input asp-for="PageQty" class="form-control">
            <span asp-validation-for="PageQty" class="text-danger"></span>
        </div>
        <div class="mb-3">
        <label asp-for="Genre"></label>
        <select asp-for="Genre" class="form-select" id="exampleSelect1">
                <option value="0">AvantGarde</option>
                <option value="1">Action</option>
                <option value="2">Detective</option>
                <option value="3">Historical</option>
                <option value="4">Love</option>
        </select>
        </div>
        <button type="submit" class="btn btn-warning" style="width:150px">
            <i class="bi bi-check-square"></i> &nbsp; Update
        </button>
        <a asp-controller="Books" asp-action="Index" class="btn btn-secondary" style="width:150px">
            <i class="bi bi-x-circle"></i> &nbsp; Cancel
        </a>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Task_004/Views/Books/Index.cshtml
@model IEnumerable<Book>
@using Task_004.Models
@using Task_004.ViewModels
@{
    ViewData["Title"] = "Books";
}

<partial name="_Notification" />
<div class="container p-3">
        <div>
        <a asp-controller="Books" class="btn btn-primary" asp-action="Create"><i class="bi bi-plus-circle"></i> &nbsp; Create a New Book</a>
        </div>
        <br />
    <table table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Books
                </th>
                <th>
                    Pages
                </th>
                <th>
                    Genre
                </th>
                <th>
                    Options
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td width="50%">
                        @item.Name
                    </td>
                    <td width="15%">
                        @item.PageQty
                    </td>
                    <td width="15%">
                        @item.Genre
                    </td>
                    <td td width="20%">
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Books" asp-action="Edit" asp-route-id="@item.Id">Edit</a><p>&nbsp;&nbsp;</p>
                            <a asp-controller="Books" asp-action="Delete" asp-route-id="@item.Id">Delete</a><p>&nbsp;&nbsp;</p>
                            <a asp-controller="Books" asp-action="Details" asp-route-id="@item.Id">Details</a><p>&nbsp;&nbsp;</p>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>